### PR TITLE
Fix compilation for SkylakeX with gcc 6.x

### LINKED ISSUE #3530: error undefined reference to `_mm512_reduce_add_pd'
Hello

I have ran into the following error while building openBLAS 0.3.19 on RHEL7 with gcc-6.3 and DYNAMIC_ARCH=1

../libopenblas_nonthreaded-r0.3.19.a(dgemm_small_kernel_nn_SKYLAKEX.o): In function `dgemm_small_kernel_nn_SKYLAKEX':
dgemm_small_kernel_nn_skylakex.c:(.text+0x2ddd): undefined reference to `_mm512_reduce_add_pd'
dgemm_small_kernel_nn_skylakex.c:(.text+0x2e1c): undefined reference to `_mm512_reduce_add_pd'
dgemm_small_kernel_nn_skylakex.c:(.text+0x2e8e): undefined reference to `_mm512_reduce_add_pd'
dgemm_small_kernel_nn_skylakex.c:(.text+0x2eea): undefined reference to `_mm512_reduce_add_pd'
dgemm_small_kernel_nn_skylakex.c:(.text+0x30c7): undefined reference to `_mm512_reduce_add_pd'
../libopenblas_nonthreaded-r0.3.19.a(dgemm_small_kernel_nn_SKYLAKEX.o):dgemm_small_kernel_nn_skylakex.c:(.text+0x3106): more undefined references to `_mm512_reduce_add_pd' follow
../libopenblas_nonthreaded-r0.3.19.a(sgemm_small_kernel_nn_SKYLAKEX.o): In function `sgemm_small_kernel_nn_SKYLAKEX':
sgemm_small_kernel_nn_skylakex.c:(.text+0x2ca3): undefined reference to `_mm512_reduce_add_ps'
sgemm_small_kernel_nn_skylakex.c:(.text+0x2cdc): undefined reference to `_mm512_reduce_add_ps'
sgemm_small_kernel_nn_skylakex.c:(.text+0x2d42): undefined reference to `_mm512_reduce_add_ps'
sgemm_small_kernel_nn_skylakex.c:(.text+0x2d95): undefined reference to `_mm512_reduce_add_ps'
sgemm_small_kernel_nn_skylakex.c:(.text+0x2f25): undefined reference to `_mm512_reduce_add_ps'
../libopenblas_nonthreaded-r0.3.19.a(sgemm_small_kernel_nn_SKYLAKEX.o):sgemm_small_kernel_nn_skylakex.c:(.text+0x2f5e): more undefined references to `_mm512_reduce_add_ps' follow
collect2: error: ld returned 1 exit status

any ideas how to get around this issue?

Regards, Roman

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes #3530 by falling back to the generic implementations of the small matrix kernels for old compilers that do not support the _mm512_reduce_add_pd intrinsic

### CODE REVIEW

**Comment by giordano** [comment]
Thanks!

File: kernel/x86_64/sgemm_small_kernel_nn_skylakex.c [hunk 1]
```diff
@@ -610,3 +611,7 @@ int CNAME(BLASLONG M, BLASLONG N, BLASLONG K, FLOAT * A, BLASLONG lda, FLOAT alp
 	}
 	return 0;
 }
+#else
+#include ../generic/gemm_small_matrix_kernel_nn.c
```
Comment (giordano) [inline kernel/x86_64/sgemm_small_kernel_nn_skylakex.c:615]: Ok, the thank was too fast.  Now I get:
```
[22:28:56] ../kernel/x86_64/sgemm_small_kernel_tn_skylakex.c:319:10: error: #include expects "FILENAME" or <FILENAME>
[22:28:56]  #include ../generic/gemm_small_matrix_kernel_tn.c
[22:28:56]           ^
```
Should have been
```c
#include "../generic/gemm_small_matrix_kernel_tn.c"
```
?
