### PR TITLE
Make SVE-enabled ARM64 targets in DYNAMIC_ARCH builds depend on a relatively recent compiler 

### LINKED ISSUE #3805: Building OpenBLAS v0.3.21 with spack stop working
See documented issue here: https://github.com/spack/spack/issues/33693

### LINKED ISSUE #3874: Aarch64 fails to build with GCC < 9 due to missing arm_sve.h
The `NEOVERSEN2` target requires the `arm_sve.h` header file:

[ 1017s] gcc -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g  -fno-strict-aliasing -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=256 -DMAX_PARALLEL_NUMBER=1 -DBUILD_BFLOAT16 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.21\" -march=armv8.2-a -mtune=cortex-a72 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=sbgemm_kernel_NEOVERSEN2 -DASMFNAME=sbgemm_kernel_NEOVERSEN2_ -DNAME=sbgemm_kernel_NEOVERSEN2_ -DCNAME=sbgemm_kernel_NEOVERSEN2 -DCHAR_NAME=\"sbgemm_kernel_NEOVERSEN2_\" -DCHAR_CNAME=\"sbgemm_kernel_NEOVERSEN2\" -DNO_AFFINITY -DTS=_NEOVERSEN2 -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_NEOVERSEN2 -DBFLOAT16 -UDOUBLE  -UCOMPLEX -c -DBFLOAT16 -UDOUBLE -UCOMPLEX ../kernel/arm64/sbgemm_kernel_8x4_neoversen2.c -o sbgemm_kernel_NEOVERSEN2.o
[ 1018s] ../kernel/arm64/sbgemm_kernel_8x4_neoversen2.c:29:10: fatal error: arm_sve.h: No such file or directory
[ 1018s]  #include <arm_sve.h>
[ 1018s]           ^~~~~~~~~~~
[ 1018s] compilation terminated.

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes #3874 (fixes #3805)

### CODE REVIEW

**Review by Mousius — APPROVED** [review]
LGTM!

File: driver/others/dynamic_arm64.c [hunk 1]
```diff
@@ -274,10 +279,12 @@ static gotoblas_t *get_coretype(void) {
           return &gotoblas_CORTEXA73;
         case 0xd0c: // Neoverse N1
           return &gotoblas_NEOVERSEN1;
+#ifndef NO_SVE
```
Comment (Mousius) [inline driver/others/dynamic_arm64.c]: Since we're aliasing these above, this isn't necessary to be guarded by `NO_SVE`?

File: driver/others/dynamic_arm64.c [hunk 2]
```diff
@@ -125,8 +125,13 @@ extern gotoblas_t  gotoblas_THUNDERX2T99;
 extern gotoblas_t  gotoblas_TSV110;
 extern gotoblas_t  gotoblas_EMAG8180;
 extern gotoblas_t  gotoblas_NEOVERSEN1;
+#ifndef NO_SVE
 extern gotoblas_t  gotoblas_NEOVERSEV1;
 extern gotoblas_t  gotoblas_NEOVERSEN2;
+#else
+#define gotoblas_NEOVERSEV1 gotoblas_ARMV8;
+#define gotoblas_NEOVERSEN2 gotoblas_ARMV8;
```
Comment (Mousius) [inline driver/others/dynamic_arm64.c]: You've got some rogue semi-colons here:

```suggestion
#define gotoblas_NEOVERSEV1 gotoblas_ARMV8
#define gotoblas_NEOVERSEN2 gotoblas_ARMV8
```

**Review by Mousius — CHANGES_REQUESTED** [review]
Realised build was failing, so I took a deeper look into this one.

#3876 fixed the build for me @martin-frbg

**Comment by martin-frbg** [comment]
Sorry for the mess, visiting family and tried to sneak in some discreet coding via the gh web editor. Will clean up ASAP

**Comment by Mousius** [comment]
> Sorry for the mess, visiting family and tried to sneak in some discreet coding via the gh web editor. Will clean up ASAP

No worries, just here to help 😸

**Comment by martin-frbg** [comment]
This has now uncovered a latent bug in the MSA support detection/handling for MIPS. To be continued, hopefully later today

**Comment by martin-frbg** [comment]
mips msa fixes to go into a separate PR, merging to get this out if the way
