### PR TITLE
Fix GEMMT transforming the input array B in some complex cases

### LINKED ISSUE #5111: C/ZGEMMT changes the inputs in the UNC case
The Z/CGEMMT routine changes the second input when calling 
```
cgemmt_("U", "N", "C", &n, &k, &alpha, A, &lda, B, &ldb, &beta, C, &ldc);
```
or 
```
zgemmt_("U", "N", "C", &n, &k, &alpha, A, &lda, B, &ldb, &beta, C, &ldc);
```

After the call B is its conjugate. 

In the `ZGEMMT` case this leads:
```
Matrix A:
(1.000000, 2.000000) (2.000000, 3.000000) (3.000000, 4.000000) 
(4.000000, 5.000000) (5.000000, 6.000000) (6.000000, 7.000000) 
(7.000000, 8.000000) (8.000000, 9.000000) (9.000000, 10.000000) 
Matrix B:
(1.000000, 1.000000) (2.000000, 2.000000) (3.000000, 3.000000) 
(4.000000, 4.000000) (5.000000, 5.000000) (6.000000, 6.000000) 
(7.000000, 7.000000) (8.000000, 8.000000) (9.000000, 9.000000) 
Matrix C:
(144.000000, 12.000000) (0.000000, 0.000000) (0.000000, 0.000000) 
(171.000000, 15.000000) (201.000000, 15.000000) (0.000000, 0.000000) 
(198.000000, 18.000000) (234.000000, 18.000000) (270.000000, 18.000000) 
After cgemmtMatrix A:
(1.000000, 2.000000) (2.000000, 3.000000) (3.000000, 4.000000) 
(4.000000, 5.000000) (5.000000, 6.000000) (6.000000, 7.000000) 
(7.000000, 8.000000) (8.000000, 9.000000) (9.000000, 10.000000) 
Matrix B:
(1.000000, -1.000000) (2.000000, -2.000000) (3.000000, -3.000000) 
(4.000000, -4.000000) (5.000000, -5.000000) (6.000000, -6.000000) 
(7.000000, -7.000000) (8.000000, -8.000000) (9.000000, -9.000000) 
```

[cgemmt_example.c.txt](https://github.com/user-attachments/files/18691046/cgemmt_example.c.txt)

[zgemmt_example.c.txt](https://github.com/user-attachments/files/18691063/zgemmt_example.c.txt)

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes #5111

### CODE REVIEW

File: interface/gemmt.c [hunk 1]
```diff
@@ -688,5 +688,19 @@ void CNAME(enum CBLAS_ORDER order, enum CBLAS_UPLO Uplo,
 
 	IDEBUG_END;
 
+/* transform B back if necessary */
```
Comment (conradsnicta) [inline interface/gemmt.c:691]: @martin-frbg Not sure if I'm interpreting the overall code correctly, but shouldn't B not be written to at all?

While GEMMT is not part of standard BLAS and only exists as an "extension", it does have a definition within MKL, where B is marked as "const".  In other words, writing to B should never happen within GEMMT (ie. no in-place operations on B).

https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-c/2025-0/cblas-gemmt.html

Comment (martin-frbg) [reply interface/gemmt.c:691]: Technically the promise is only that the inputs will be unchanged on exit, IMHO what happens behind closed doors is implementation-defined. And the current implementation is inefficient and needs to be redone eventually. It was only a quick, GEMV-based hack to provide _any_ support for GEMMT at all when the Reference implementation did not yet have it.

Comment (conradsnicta) [reply interface/gemmt.c:691]: Agree that it's better to have something rather than nothing.  Looking purely at the implementation side, writing to B would still be ill-advised as it's promised as "const" by MKL.  One possible case is that B is shared with another thread (say in a non-OpenBLAS function), which expects it unchanged.  There may also be a possible performance degradation due to cache pollution stemming from unnecessary writes to B.

Comment (martin-frbg) [reply interface/gemmt.c:691]: As I say the entire implementation is an ugly hack and needs to be replaced - but that is another can of worms, namely #4921, and I can only do so much in a day (and sometimes not even that)

Comment (conradsnicta) [reply interface/gemmt.c:691]: https://xkcd.com/2347/
