### PR TITLE
Fix DYNAMIC_ARCH compilation on POWER with gcc <11

### LINKED ISSUE #3074: OpenBLAS 0.3.13 fails to build on ppc64le / gcc 8.2
I'm building OpenBLAS 0.3.13 using Spack on a POWER8 machine running Debian 10.

Build fails because of the new POWER10 dynamic support:

```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'CC=/grid5000/spack/lib/spack/env/gcc/gcc' 'FC=/grid5000/spack/lib/spack/env/gcc/gfortran' 'MAKE_NB_JOBS=0' 'DYNAMIC_ARCH=1' 'USE_OPENMP=0' 'USE_THREAD=0' 'RANLIB=ranlib' 'libs' 'netlib' 'shared'                        

2 errors found in build log:
     1190    /grid5000/spack/lib/spack/env/gcc/gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=160 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=
             1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.13\" -Ofast -mcpu=power8 -mtune=power8 -mvsx  -fno-fast-math -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=openblas_env -DASMFNAME=openblas_env_ -DNAME=openblas_
             env_ -DCNAME=openblas_env -DCHAR_NAME=\"openblas_env_\" -DCHAR_CNAME=\"openblas_env\" -DNO_AFFINITY -I../.. -c openblas_env.c -o openblas_env.o                                                                                 
     1191    /grid5000/spack/lib/spack/env/gcc/gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=160 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=
             1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.13\" -Ofast -mcpu=power8 -mtune=power8 -mvsx  -fno-fast-math -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=dynamic_power -DASMFNAME=dynamic_power_ -DNAME=dynamic
             _power_ -DCNAME=dynamic_power -DCHAR_NAME=\"dynamic_power_\" -DCHAR_CNAME=\"dynamic_power\" -DNO_AFFINITY -I../..   -c -o dynamic_power.o dynamic_power.c                                                                       
     1192    dynamic_power.c:9:1: warning: multi-line comment [-Wcomment]
     1193     //#if (!defined __GNUC__) || ( __GNUC__ >= 11) \
     1194     ^
     1195    dynamic_power.c: In function 'gotoblas_dynamic_init':
  >> 1196    dynamic_power.c:57:6: error: cpu 'power10' is an invalid argument to builtin '__builtin_cpu_is'
     1197      if (__builtin_cpu_is("power10"))
     1198          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  >> 1199    make[1]: *** [<builtin>: dynamic_power.o] Error 1
     1200    make[1]: *** Waiting for unfinished jobs....
     1201    make[1]: Leaving directory '/var/spack/stage/root/spack-stage-openblas-0.3.13-57p57xjbiiv757vjq4uickpldoq4vcfy/spack-src/driver/others'                                                                                         
     1202    make: *** [Makefile:165: libs] Error 1
```

Here are the versions:

```
# gcc --version
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# ld --version
GNU ld (GNU Binutils for Debian) 2.31.1
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

I browsed other issues, and as far as I can tell, POWER10 support is supposed to be disabled with old versions of GCC. Not sure what's up.

### PR DESCRIPTION
**Pull request by martin-frbg**
the "power10" argument to the __builtin_cpu_is() check is only available in gcc builds more recent than 10.2
fixes #3074

### CODE REVIEW

File: driver/others/dynamic_power.c [hunk 1]
```diff
@@ -202,7 +202,7 @@ static gotoblas_t *get_coretype(void) {
 		return &gotoblas_POWER10;
 #endif
 	/* Fall back to the POWER9 implementation if the toolchain is too old or the MMA feature is not set */
-#if (!defined __GNUC__) || ( __GNUC__ >= 6)
+#if (!defined __GNUC__) || ( __GNUC__ >= 11)
```
Comment (RajalakshmiSR) [inline driver/others/dynamic_power.c]: @martin-frbg Since its just a fall back to POWER9, can we just move lines if (__builtin_cpu_is("power10"))
                return &gotoblas_POWER9;  inside ifdef HAVE_P10_SUPPORT after line 202.

Comment (martin-frbg) [reply driver/others/dynamic_power.c]: HAVE_P10_SUPPORT depends on having a very recent ld version in addition to new gcc, so a bit more than required for a fallback to POWER9

Comment (RajalakshmiSR) [reply driver/others/dynamic_power.c]: @martin-frbg Then should we also consider gcc 10.2 here?
#if (!defined __GNUC__) || ( __GNUC__ >= 11)  || (__GNUC__ == 10 && __GNUC_MINOR__ >= 2)

Comment (martin-frbg) [reply driver/others/dynamic_power.c]: I do not think that 10.2 (released in july) already contains a patch that was committed to the gcc mainline at the end of june ?

Comment (RajalakshmiSR) [reply driver/others/dynamic_power.c]: Link for gcc backport: https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=41b504e91e5cd0fdce36b7306ce42dd592c401f2

**Comment by RajalakshmiSR** [comment]
@martin-frbg LGTM. Thanks!
